### ISSUE TITLE
Challenges getting the ProtonMail bridge to work with Paperless-NGX

### ISSUE THREAD

**Issue by ZuluPilgrim** [shenxn/protonmail-bridge-docker#101]
I have used the following to setup the ProtonMail Bridge to work with Paperless.

```
version: "3.4"

networks:
  my-network:

services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    networks:
      - my-network
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    ports:
      - "8000:8000"
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'

  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    networks:
      - my-network

    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: ghcr.io/paperless-ngx/tika:latest
    restart: unless-stopped
    networks:
      - my-network


  protonmail-bridge:
    image: shenxn/protonmail-bridge
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    networks:
      - my-network
    volumes:
      - protonmail:/root
volumes:
  data:
  media:
  pgdata:
  redisdata:
  protonmail:
    name: protonmail
```
I followed this approach after reading: [https://www.richardneililagan.com/posts/paperless-ngx-with-proton-mail/](https://www.richardneililagan.com/posts/paperless-ngx-with-proton-mail/)
).

Paperless requires the below values but when I hit test I am told it cannot connect to the mail server. What should I try for the IMAP server address or is there something else that I am missing?
![image](https://github.com/shenxn/protonmail-bridge-docker/assets/111164245/985ef3b3-8da7-4bcf-8fa2-a0dc2980b69e)
