### ISSUE TITLE
Thunderbird "unable to log in at server"

### ISSUE THREAD

**Issue by wallaby-gopher** [shenxn/protonmail-bridge-docker#121]
Hello, Thunderbird can detect the bridge's settings, but can't seem to login. I had followed this guide: [https://hagensieker.com/2021/11/18/protonmail-bridge-on-unraid/](https://hagensieker.com/2021/11/18/protonmail-bridge-on-unraid/) and this guide: [https://proton.me/support/protonmail-bridge-clients-windows-thunderbird](https://proton.me/support/protonmail-bridge-clients-windows-thunderbird)
Here you can see the info prompt from cli

![Image](https://github.com/user-attachments/assets/fe2d4414-ecb5-4a9a-b973-115c623f811d)
Here you can see thunderbird detecting settings with the username/pass from the desktop bridge:

![Image](https://github.com/user-attachments/assets/9cb18b9c-0c72-4f41-b20d-6160d0ef04f8)

I have also tried the cli info password and proton account password just to see, no difference. 
I have verified the containers can talk to each other

![Image](https://github.com/user-attachments/assets/8f44f930-a0a6-4017-807a-b3af062ce1e3)

See compose below:
```
networks:
  bridge_network:
    name: bridge_network
  backend_network:
    name: backend_network
    external: true
volumes:
#email
  thunderbird:
  protonmail:
services:
  #for local emails
  thunderbird:
    image: jlesage/thunderbird
    container_name: thunderbird
    networks:
      - bridge_network
      - backend_network
    ports:
      - "5800:5800"
    volumes:
      - thunderbird:/config:rw
    restart: unless-stopped

  #for thunderbird to get protonmail
  protonmail-bridge:
    image: shenxn/protonmail-bridge
    container_name: protonmail-bridge
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    restart: unless-stopped
    networks:
      - backend_network
    volumes:
      - protonmail:/root
```

and the error: 

![Image](https://github.com/user-attachments/assets/a2427229-0039-4b87-bcce-63995817c162)
there are no errors in either container.

Any ideas?
