### ISSUE TITLE
Not seeing expected results with docker-compose

### ISSUE THREAD

**Issue by aybry** [shenxn/protonmail-bridge-docker#30]
First of all, thanks for your work!

I followed the readme and successfully connected my account in the container using the command under "Initialization". 

When I use the "Run" command, the container starts correctly and when I `docker exec -it <name> bash` into the container, I see that `protonmail-bridge` is running and the credentials are still valid. 

However, when trying to start the container using docker-compose within another project that will be using the bridge, the same can't be said. Here is the relevant part of my `docker-compose.yaml`:

```
  protonmail-bridge:
    container_name: protonmail-bridge
    image: shenxn/protonmail-bridge
    restart: unless-stopped
    ports:
      - 127.0.0.1:1025:25/tcp
    volumes:
      - protonmail:/root
```

When I enter the container and try to run `protonmail-bridge --cli`, I see the following:

```
WARN[0000] Failed to add test credentials to keychain    error="exit status 1: gpg: protonmail-bridge: skipped: No public key\ngpg: [stdin]: encryption failed: No public key\nPassword encryption aborted.\n" helper="*pass.Pass"
```

I expect that the "Issue" I am raising lies more with me and my inexperience with Docker/docker-compose, but hope it's OK to ask for help here. What do I need to change in my `docker-compose.yaml` for it to use the container I `init`ed?

Thanks!
