### ISSUE TITLE
No password manager?

### ISSUE THREAD

**Issue by ZerkerEOD** [shenxn/protonmail-bridge-docker#61]
I am having so many issues setting this up. I am trying to use docker-compose. I start it up and can't get anything running. I followed a link and killed both proton processes and then ran ./entrypoint.sh after making it executable. It starts up with the following errors:

```
+ [[ '' == init ]]
+ rm -f faketty
+ socat TCP-LISTEN:143,fork TCP:127.0.0.1:1143
+ mkfifo faketty
+ socat TCP-LISTEN:25,fork TCP:127.0.0.1:1025
+ protonmail-bridge --cli
+ cat faketty
2022/06/25 07:04:28 socat[4647] E bind(5, {AF=2 0.0.0.0:25}, 16): Address already in use
2022/06/25 07:04:28 socat[4648] E bind(5, {AF=2 0.0.0.0:143}, 16): Address already in use
WARN[0000] Failed to add test credentials to keychain    error="failed to open dbus connection: exec: \"dbus-launch\": executable file not found in $PATH" helper="*keychain.SecretServiceDBusHelper"
WARN[0000] Failed to add test credentials to keychain    error="pass not initialized: exit status 1: Error: password store is empty. Try \"pass init\".\n" helper="*pass.Pass"
ERRO[Jun 25 07:04:28.543] Could not list credentials                    error="no keychain" pkg=credentials
ERRO[Jun 25 07:04:28.543] Could not load all users from credentials store  error="no keychain" pkg=users

            Welcome to ProtonMail Bridge interactive shell
                              ___....___
    ^^                __..-:'':__:..:__:'':-..__
                  _.-:__:.-:'':  :  :  :'':-.:__:-._
                .':.-:  :  :  :  :  :  :  :  :  :._:'.
             _ :.':  :  :  :  :  :  :  :  :  :  :  :'.: _
            [ ]:  :  :  :  :  :  :  :  :  :  :  :  :  :[ ]
            [ ]:  :  :  :  :  :  :  :  :  :  :  :  :  :[ ]
   :::::::::[ ]:__:__:__:__:__:__:__:__:__:__:__:__:__:[ ]:::::::::::
   !!!!!!!!![ ]!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!![ ]!!!!!!!!!!!
   ^^^^^^^^^[ ]^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[ ]^^^^^^^^^^^
            [ ]                                        [ ]
            [ ]                                        [ ]
      jgs   [ ]                                        [ ]
    ~~^_~^~/   \~^-~^~ _~^-~_^~-^~_^~~-^~_~^~-~_~-^~_^/   \~^ ~~_ ^
ProtonMail Bridge is not able to detect a supported password manager
(secret-service or pass). Please install and set up a supported password manager
and restart the application.
```

I then tried the install.sh script and ran the entrypoint.sh again but it came up with the same errors. 

Here is my docker-config 
```
    protonmail:
        image: shenxn/protonmail-bridge
        container_name: protonmail
        hostname: protonmail
        ports:
            - "127.0.0.1:1025:25/tcp"
            - "127.0.0.1:1143:143/tcp"
        volumes:
            - ./protonmail:/root
        restart: unless-stopped
```

any help would be appreciated.
