### ISSUE TITLE
Docker compose init

### ISSUE THREAD

**Issue by MozkaGit** [shenxn/protonmail-bridge-docker#91]
Hello, when I use docker-compose I can't get past the init phase. When I run it I can't enter the `login` or any others cli commands because I don't have any prompt.

Inside the container shell I can't run `./entrypoint.sh login` either, because I get this error: `Failed to create lock file; another instance is running.`

![image](https://github.com/shenxn/protonmail-bridge-docker/assets/43102748/e54a2499-fcfa-493e-9698-5bf26d4bf3e9)

This is my compose config : 

```
version : "3.8"
services:
  proton:
    image: shenxn/protonmail-bridge
    container_name: protonmail-bridge
    volumes:
      - ./protonmail:/root
    ports:
      - 1025:25/tcp
      - 1143:143/tcp
    stdin_open: true
    tty: true
    command: init
    restart: unless-stopped
```

I dont have this issue when I simply use `docker run` cli command.

Please any help would be appreciated.
